source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "rack-attack"
gem "ruby-openai", "~> 7.0", require: "openai"
gem "kaminari"
gem "bcrypt", "~> 3.1.7"

gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "webmock"
end
