from enum import Enum


class UserStatus(str, Enum):
    PENDING = "PENDING" # 가입 대기
    ACTIVE = "ACTIVE" # 가입 완료
    SUSPENDED = "SUSPENDED" # 계정 정지
    WITHDRAWN = "WITHDRAWN" # 회원 탈퇴


ACCESS_TOKEN_TTL_SECONDS = 15 * 60
REFRESH_TOKEN_TTL_SECONDS = 14 * 24 * 60 * 60

VERIFY_CODE_TTL_SECONDS = 5 * 60
RESEND_COOLDOWN_SECONDS = 60
MAX_VERIFY_ATTEMPTS = 5

LOGIN_FAIL_TTL_SECONDS = 15 * 60
MAX_LOGIN_FAILS = 5
